import type { SolutionCard } from "@/types";

export const marketplaceSolutions: SolutionCard[] = [
  {
    id: "paletizado-raas",
    title: "Paletizado como Servicio",
    category: "Paletizado",
    description: "Automatiza tu proceso de paletizado sin inversión inicial. Cobots de alta carga con gripper adaptable a múltiples formatos.",
    industries: ["Alimentos y bebidas", "Retail", "Manufactura", "Químico"],
    modalities: ["RaaS mensual", "RaaS anual", "Compra"],
    components: ["Cobot UR10e / UR20", "Gripper neumático o eléctrico", "Mesa de paletizado", "Software de programación", "Soporte 24/7"],
    benefits: ["Sin CAPEX inicial", "Productividad +40%", "Operación 3 turnos", "ROI < 18 meses"],
    icon: "Package",
    gradient: "from-blue-600 to-blue-800",
  },
  {
    id: "pick-place",
    title: "Pick & Place Industrial",
    category: "Pick & Place",
    description: "Solución completa para selección y posicionamiento de piezas con visión artificial integrada y alta cadencia.",
    industries: ["Electrónica", "Automotriz", "Farmacéutico", "Plásticos"],
    modalities: ["RaaS mensual", "PoC", "Compra"],
    components: ["Robot delta o SCARA", "Sistema de visión 2D/3D", "Conveyor integrado", "Software de clasificación"],
    benefits: ["Cadencia +500 ppm", "Precisión ±0.1mm", "Cero errores de selección", "Trazabilidad completa"],
    icon: "Crosshair",
    gradient: "from-indigo-600 to-purple-700",
  },
  {
    id: "soldadura-robotizada",
    title: "Soldadura Robotizada",
    category: "Soldadura",
    description: "Celdas de soldadura MIG/TIG/Plasma multimarca. Calidad constante, alta productividad y trazabilidad de cada cordón.",
    industries: ["Metalmecánica", "Construcción", "Automotriz", "Energía"],
    modalities: ["RaaS anual", "Compra", "Leasing"],
    components: ["Robot 6 ejes", "Fuente de soldadura integrada", "Posicionador rotativo", "Sistema de antorcha", "Extracción de humos"],
    benefits: ["Calidad homogénea", "Producción +60%", "Sin riesgos ergonómicos", "Certificación de calidad"],
    icon: "Zap",
    gradient: "from-orange-500 to-red-600",
  },
  {
    id: "machine-tending",
    title: "Machine Tending Autónomo",
    category: "Machine Tending",
    description: "Alimentación y descarga autónoma de máquinas CNC, inyectoras y prensas. El robot trabaja los 3 turnos sin intervención.",
    industries: ["Manufactura", "Automotriz", "Plásticos", "Fundición"],
    modalities: ["RaaS mensual", "RaaS anual", "PoC"],
    components: ["Cobot UR o robot industrial", "Gripper adaptable", "Interfaz con máquina (IO/Ethernet)", "Software de ciclo"],
    benefits: ["Turnos nocturnos sin operario", "Reducción de tiempos muertos", "Consistencia de ciclo", "Integración con MES/ERP"],
    icon: "Settings",
    gradient: "from-cyan-600 to-blue-700",
  },
  {
    id: "vision-artificial",
    title: "Inspección con Visión IA",
    category: "Visión IA",
    description: "Sistema de inspección visual con inteligencia artificial para detección de defectos en línea, clasificación y control de calidad.",
    industries: ["Farmacéutico", "Alimentos", "Electrónica", "Automotriz"],
    modalities: ["RaaS mensual", "Compra", "PoC"],
    components: ["Cámara industrial 2D/3D", "Iluminación especializada", "Software IA de inspección", "Integración con PLC/SCADA", "Dashboard de calidad"],
    benefits: ["Detección >99.5%", "0 falsas alarmas", "Trazabilidad 100%", "Reportes en tiempo real"],
    icon: "Eye",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "amr-logistica",
    title: "AMR para Logística Interna",
    category: "Logística AMR",
    description: "Robots móviles autónomos para transporte interno de materiales, alimentación de líneas y gestión de inventario.",
    industries: ["Logística", "E-commerce", "Manufactura", "Retail"],
    modalities: ["RaaS mensual", "RaaS anual", "Leasing"],
    components: ["AMR de carga o estantería", "Sistema de navegación SLAM", "Software de gestión de flota", "Integración con WMS"],
    benefits: ["Sin modificar planta", "Rutas dinámicas", "Integración WMS", "Escalable on-demand"],
    icon: "Truck",
    gradient: "from-violet-600 to-indigo-700",
  },
  {
    id: "humanoides",
    title: "Robots Humanoides Productivos",
    category: "Humanoides",
    description: "Integración de robots humanoides de última generación para tareas de manipulación compleja, ensamble y soporte en planta.",
    industries: ["Manufactura avanzada", "Logística", "Electrónica", "Defensa"],
    modalities: ["PoC", "RaaS anual", "Piloto"],
    components: ["Robot humanoide (Unitree / 1X / Figure)", "Sistema de visión 3D", "Software de control de tareas", "Integración de seguridad"],
    benefits: ["Adaptación a entornos existentes", "Sin rediseño de planta", "Tareas complejas sin jigs", "Tecnología de punta"],
    icon: "Bot",
    gradient: "from-slate-600 to-zinc-800",
  },
  {
    id: "digital-twin",
    title: "Digital Twin & Simulación",
    category: "Simulación",
    description: "Simulación de procesos robóticos antes de implementar. Validación de layout, tiempos de ciclo, alcance y factibilidad sin riesgos.",
    industries: ["Todos los sectores"],
    modalities: ["Servicio de consultoría", "PoC", "Proyecto"],
    components: ["Software de simulación (RoboDK / KUKA.Sim)", "Modelo digital del proceso", "Análisis de tiempos de ciclo", "Informe de factibilidad"],
    benefits: ["0 riesgo en implementación", "Reducción de tiempo de puesta en marcha", "Optimización previa", "Presentación a directivos"],
    icon: "Monitor",
    gradient: "from-blue-700 to-primary",
  },
];

export const marketplaceCategories = [
  "Todos",
  "Paletizado",
  "Pick & Place",
  "Soldadura",
  "Machine Tending",
  "Visión IA",
  "Logística AMR",
  "Humanoides",
  "Simulación",
];
